# Generated by Django 3.0.6 on 2020-06-22 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiz',
            name='benutzer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
