# Generated by Django 3.0.6 on 2020-06-24 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200622_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiz',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
