# Generated by Django 3.0.6 on 2020-06-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notiz_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notiz',
            name='saved',
        ),
    ]
