# Generated by Django 3.0.6 on 2020-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notiz_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiz',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
