# Generated by Django 3.0.6 on 2020-05-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datei',
            options={'verbose_name_plural': 'Dateien'},
        ),
    ]
