# Generated by Django 3.0.6 on 2020-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20200603_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(upload_to='data/1/'),
        ),
    ]
