# Generated by Django 3.0.6 on 2020-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20200603_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(upload_to='data/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
