# Generated by Django 3.0.6 on 2020-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20200617_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(upload_to="data/<class 'django.contrib.auth.models.User'>/"),
        ),
    ]
