# Generated by Django 3.0.6 on 2020-06-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20200617_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(upload_to='data/<function AbstractBaseUser.get_username at 0x042A1B20>/'),
        ),
    ]
