# Generated by Django 3.0.6 on 2020-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20200617_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='datei',
            name='benutzername',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(upload_to='data/<django.db.models.fields.CharField>/'),
        ),
    ]
