# Generated by Django 3.0.7 on 2020-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_auto_20200701_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(blank=True, null=True, upload_to='data/<django.db.models.fields.CharField>/'),
        ),
    ]
