# Generated by Django 3.0.7 on 2020-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_auto_20200701_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(blank=True, null=True, upload_to='data/adjkncvir1495kgsiqiy/'),
        ),
    ]
