# Generated by Django 3.0.7 on 2020-07-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_auto_20200701_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datei',
        ),
    ]
