# Generated by Django 3.0.7 on 2020-07-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0022_delete_datei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.FileField(blank=True, null=True, upload_to='data/adjkncvir1495kgsiqiy/')),
                ('name', models.CharField(max_length=200)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datei', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dateien',
            },
        ),
    ]
