# Generated by Django 3.0.7 on 2020-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_datei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datei',
            name='datei',
            field=models.FileField(blank=True, null=True, upload_to='data/HXJA22JSU2U5V1JVPLPW/'),
        ),
    ]
