# Generated by Django 3.0.6 on 2020-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('untertitel', models.CharField(max_length=250)),
                ('inhalt', models.TextField()),
            ],
        ),
    ]
